// ──────────────────────────────────────────────────────────
// Styled-Components Resolver — Best-effort source mapping
// ──────────────────────────────────────────────────────────
//
// Styled-components generate class names with an `sc-` prefix
// at runtime. This resolver attempts to map them back to source
// files by searching for `styled.xxx` or `styled(Component)`
// patterns in the codebase.
//
// Limitations:
//   - Cannot guarantee 1:1 mapping (runtime classes are hashed)
//   - Relies on heuristic file/component name matching
//   - Works best with named exports and consistent naming
//
// ──────────────────────────────────────────────────────────

import * as vscode from "vscode";

export type StyledSource = {
  file: vscode.Uri;
  line: number;
  column: number;
  componentName: string;
  styledTag: string; // e.g. "div", "button", "Component"
  type: "styled-components" | "emotion";
};

// ── Class name detection ──────────────────────────────────

/**
 * Check if a class name was generated by styled-components.
 * Patterns:
 *   - `sc-XXXXXX` (styled-components v5+)
 *   - `sc-XXXXXX-N` (with index)
 *   - `css-XXXXXX` (emotion)
 */
export function isStyledClass(className: string): boolean {
  return /^sc-[a-zA-Z0-9]+/.test(className) || /^css-[a-zA-Z0-9]+/.test(className);
}

/**
 * Extract the component hash from a styled-components class name.
 * `sc-bczRLJ` -> `bczRLJ`
 */
function extractHash(className: string): string | null {
  const match = className.match(/^(?:sc|css)-([a-zA-Z0-9]+)/);
  return match ? match[1] : null;
}

// ── Source file scanning ──────────────────────────────────

// Pattern: const Foo = styled.div`...`
const STYLED_DOT_PATTERN = /(?:const|let|var|export\s+(?:const|let|var)?)\s+(\w+)\s*=\s*styled\.(\w+)/g;

// Pattern: const Foo = styled(Component)`...`
const STYLED_CALL_PATTERN = /(?:const|let|var|export\s+(?:const|let|var)?)\s+(\w+)\s*=\s*styled\((\w+)\)/g;

// Pattern: emotion's css`` or styled``
const EMOTION_PATTERN = /(?:const|let|var|export\s+(?:const|let|var)?)\s+(\w+)\s*=\s*(?:styled|css)\s*(?:\.\w+|\(\w+\))?`/g;

type StyledDeclaration = {
  componentName: string;
  styledTag: string;
  line: number;
  column: number;
};

/**
 * Scan a file for styled-component declarations.
 * Returns all found declarations with their positions.
 */
function scanFileForStyledDeclarations(text: string): StyledDeclaration[] {
  const results: StyledDeclaration[] = [];
  const lines = text.split("\n");

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];

    // styled.tag pattern
    let match: RegExpExecArray | null;
    STYLED_DOT_PATTERN.lastIndex = 0;
    while ((match = STYLED_DOT_PATTERN.exec(line)) !== null) {
      results.push({
        componentName: match[1],
        styledTag: match[2],
        line: i + 1,
        column: match.index,
      });
    }

    // styled(Component) pattern
    STYLED_CALL_PATTERN.lastIndex = 0;
    while ((match = STYLED_CALL_PATTERN.exec(line)) !== null) {
      results.push({
        componentName: match[1],
        styledTag: match[2],
        line: i + 1,
        column: match.index,
      });
    }

    // Emotion pattern
    EMOTION_PATTERN.lastIndex = 0;
    while ((match = EMOTION_PATTERN.exec(line)) !== null) {
      // Avoid duplicates from the patterns above
      const name = match[1];
      if (!results.some((r) => r.componentName === name && r.line === i + 1)) {
        results.push({
          componentName: name,
          styledTag: "unknown",
          line: i + 1,
          column: match.index,
        });
      }
    }
  }

  return results;
}

/**
 * Resolve a styled-components class name to its source declaration.
 *
 * Strategy:
 *   1. Identify the class as styled-components via `sc-` prefix
 *   2. If a `componentDisplayName` is provided (from data attributes
 *      or React DevTools), search for that exact component name
 *   3. Otherwise, scan all source files for styled declarations
 *      and return all matches (best-effort)
 *
 * @param className - The runtime class name (e.g. `sc-bczRLJ`)
 * @param componentDisplayName - Optional display name from React tree
 */
export async function resolveStyledComponent(
  className: string,
  componentDisplayName?: string
): Promise<StyledSource | null> {
  if (!isStyledClass(className)) return null;

  const isEmotion = className.startsWith("css-");

  // Search source files for styled-component declarations
  const sourceFiles = await vscode.workspace.findFiles(
    "**/*.{tsx,ts,jsx,js}",
    "**/node_modules/**",
    200
  );

  for (const file of sourceFiles) {
    const doc = await vscode.workspace.openTextDocument(file);
    const text = doc.getText();

    // Quick check: does this file use styled-components at all?
    if (!text.includes("styled.") && !text.includes("styled(") && !text.includes("css`")) {
      continue;
    }

    const declarations = scanFileForStyledDeclarations(text);
    if (declarations.length === 0) continue;

    // If we have a display name, try to match it
    if (componentDisplayName) {
      const match = declarations.find(
        (d) => d.componentName === componentDisplayName ||
               d.componentName.toLowerCase() === componentDisplayName.toLowerCase()
      );
      if (match) {
        return {
          file,
          line: match.line,
          column: match.column,
          componentName: match.componentName,
          styledTag: match.styledTag,
          type: isEmotion ? "emotion" : "styled-components",
        };
      }
    }

    // If the file name hints at the component, return the first declaration
    const fileName = file.fsPath.split("/").pop()?.replace(/\.\w+$/, "") || "";
    if (componentDisplayName && fileName.toLowerCase().includes(componentDisplayName.toLowerCase())) {
      const first = declarations[0];
      return {
        file,
        line: first.line,
        column: first.column,
        componentName: first.componentName,
        styledTag: first.styledTag,
        type: isEmotion ? "emotion" : "styled-components",
      };
    }
  }

  return null;
}

/**
 * Find ALL styled-component declarations in the workspace.
 * Useful for building an index / cache.
 */
export async function indexStyledComponents(): Promise<
  Array<StyledSource & { declarations: StyledDeclaration[] }>
> {
  const results: Array<StyledSource & { declarations: StyledDeclaration[] }> = [];

  const sourceFiles = await vscode.workspace.findFiles(
    "**/*.{tsx,ts,jsx,js}",
    "**/node_modules/**",
    500
  );

  for (const file of sourceFiles) {
    const doc = await vscode.workspace.openTextDocument(file);
    const text = doc.getText();

    if (!text.includes("styled.") && !text.includes("styled(")) continue;

    const declarations = scanFileForStyledDeclarations(text);
    if (declarations.length > 0) {
      const first = declarations[0];
      results.push({
        file,
        line: first.line,
        column: first.column,
        componentName: first.componentName,
        styledTag: first.styledTag,
        type: "styled-components",
        declarations,
      });
    }
  }

  return results;
}
